/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type PortfolioMediaReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "portfolioMedia";
};

export type PortfolioProjectReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "portfolioProject";
};

export type PortfolioProject = {
  _id: string;
  _type: "portfolioProject";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  sourceUrl?: string;
  order?: number;
  column?: 1 | 2;
  summary?: string;
  body?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal";
    listItem?: never;
    markDefs?: null;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  tags?: Array<string>;
  services?: Array<string>;
  tools?: Array<string>;
  icon?: PortfolioMediaReference;
  cover?: PortfolioMediaReference;
  coverRatio?: number;
  hero?: PortfolioMediaReference;
  gallery?: Array<
    | {
        title?: string;
        _type: "galleryHeading";
        _key: string;
      }
    | {
        items?: Array<
          {
            _key: string;
          } & PortfolioMediaReference
        >;
        _type: "galleryRow";
        _key: string;
      }
  >;
  related?: Array<
    {
      _key: string;
    } & PortfolioProjectReference
  >;
  seoTitle?: string;
  seoDescription?: string;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type PortfolioPage = {
  _id: string;
  _type: "portfolioPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  key?: "home" | "about" | "notFound";
  sourceUrl?: string;
  headline?: string;
  introduction?: string;
  ctaLabel?: string;
  servicesHeading?: string;
  clientsHeading?: string;
  galleryHeading?: string;
  closingHeading?: string;
  storyHeading?: string;
  story?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal";
    listItem?: never;
    markDefs?: null;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  approachHeading?: string;
  approach?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal";
    listItem?: never;
    markDefs?: null;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  glow?: PortfolioMediaReference;
  photos?: Array<
    {
      _key: string;
    } & PortfolioMediaReference
  >;
  collage?: Array<
    {
      _key: string;
    } & PortfolioMediaReference
  >;
  logos?: Array<
    {
      _key: string;
    } & PortfolioMediaReference
  >;
  gallery?: Array<
    {
      _key: string;
    } & PortfolioMediaReference
  >;
  resumeUrl?: string;
  career?: Array<{
    role?: string;
    company?: string;
    dates?: string;
    icon?: PortfolioMediaReference;
    _type: "position";
    _key: string;
  }>;
  seoTitle?: string;
  seoDescription?: string;
};

export type SiteSettings = {
  _id: string;
  _type: "siteSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  sourceUrl?: string;
  name?: string;
  email?: string;
  contactLabel?: string;
  availability?: string;
  socialLabel?: string;
  seoTitle?: string;
  seoDescription?: string;
  socials?: Array<{
    label?: string;
    url?: string;
    icon?: PortfolioMediaReference;
    darkIcon?: PortfolioMediaReference;
    _type: "social";
    _key: string;
  }>;
  copyIcon?: PortfolioMediaReference;
  darkCopyIcon?: PortfolioMediaReference;
};

export type PortfolioService = {
  _id: string;
  _type: "portfolioService";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  description?: string;
  icons?: Array<
    {
      _key: string;
    } & PortfolioMediaReference
  >;
  order?: number;
  sourceUrl?: string;
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type SanityFileAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.fileAsset";
};

export type PortfolioMedia = {
  _id: string;
  _type: "portfolioMedia";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  alt?: string;
  sourceUrl?: string;
  kind?: "image" | "video";
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  clip?: {
    asset?: SanityFileAssetReference;
    media?: unknown;
    _type: "file";
  };
  aspectRatio?: number;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type Project = {
  _id: string;
  _type: "project";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  summary?: string;
  website?: string;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | PortfolioMediaReference
  | PortfolioProjectReference
  | PortfolioProject
  | Slug
  | PortfolioPage
  | SiteSettings
  | PortfolioService
  | SanityImageAssetReference
  | SanityFileAssetReference
  | PortfolioMedia
  | SanityImageCrop
  | SanityImageHotspot
  | Project
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: ../web/src/lib/sanity.ts
// Variable: SITE_QUERY
// Query: {  "settings": *[_type == "siteSettings"][0],  "pages": *[_type == "portfolioPage"],  "projects": *[_type == "portfolioProject" && defined(slug.current)] | order(order asc),  "services": *[_type == "portfolioService"] | order(order asc),  "media": *[_type == "portfolioMedia"] {    _id, title, alt, kind, aspectRatio,    "url": coalesce(image.asset->url, clip.asset->url),    "width": image.asset->metadata.dimensions.width,    "height": image.asset->metadata.dimensions.height  }}
export type SITE_QUERY_RESULT = {
  settings: {
    _id: string;
    _type: "siteSettings";
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    sourceUrl?: string;
    name?: string;
    email?: string;
    contactLabel?: string;
    availability?: string;
    socialLabel?: string;
    seoTitle?: string;
    seoDescription?: string;
    socials?: Array<{
      label?: string;
      url?: string;
      icon?: PortfolioMediaReference;
      darkIcon?: PortfolioMediaReference;
      _type: "social";
      _key: string;
    }>;
    copyIcon?: PortfolioMediaReference;
    darkCopyIcon?: PortfolioMediaReference;
  } | null;
  pages: Array<{
    _id: string;
    _type: "portfolioPage";
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    title?: string;
    key?: "about" | "home" | "notFound";
    sourceUrl?: string;
    headline?: string;
    introduction?: string;
    ctaLabel?: string;
    servicesHeading?: string;
    clientsHeading?: string;
    galleryHeading?: string;
    closingHeading?: string;
    storyHeading?: string;
    story?: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "normal";
      listItem?: never;
      markDefs?: null;
      level?: number;
      _type: "block";
      _key: string;
    }>;
    approachHeading?: string;
    approach?: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "normal";
      listItem?: never;
      markDefs?: null;
      level?: number;
      _type: "block";
      _key: string;
    }>;
    glow?: PortfolioMediaReference;
    photos?: Array<
      {
        _key: string;
      } & PortfolioMediaReference
    >;
    collage?: Array<
      {
        _key: string;
      } & PortfolioMediaReference
    >;
    logos?: Array<
      {
        _key: string;
      } & PortfolioMediaReference
    >;
    gallery?: Array<
      {
        _key: string;
      } & PortfolioMediaReference
    >;
    resumeUrl?: string;
    career?: Array<{
      role?: string;
      company?: string;
      dates?: string;
      icon?: PortfolioMediaReference;
      _type: "position";
      _key: string;
    }>;
    seoTitle?: string;
    seoDescription?: string;
  }>;
  projects: Array<{
    _id: string;
    _type: "portfolioProject";
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    title?: string;
    slug?: Slug;
    sourceUrl?: string;
    order?: number;
    column?: 1 | 2;
    summary?: string;
    body?: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "normal";
      listItem?: never;
      markDefs?: null;
      level?: number;
      _type: "block";
      _key: string;
    }>;
    tags?: Array<string>;
    services?: Array<string>;
    tools?: Array<string>;
    icon?: PortfolioMediaReference;
    cover?: PortfolioMediaReference;
    coverRatio?: number;
    hero?: PortfolioMediaReference;
    gallery?: Array<
      | {
          title?: string;
          _type: "galleryHeading";
          _key: string;
        }
      | {
          items?: Array<
            {
              _key: string;
            } & PortfolioMediaReference
          >;
          _type: "galleryRow";
          _key: string;
        }
    >;
    related?: Array<
      {
        _key: string;
      } & PortfolioProjectReference
    >;
    seoTitle?: string;
    seoDescription?: string;
  }>;
  services: Array<{
    _id: string;
    _type: "portfolioService";
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    title?: string;
    description?: string;
    icons?: Array<
      {
        _key: string;
      } & PortfolioMediaReference
    >;
    order?: number;
    sourceUrl?: string;
  }>;
  media: Array<{
    _id: string;
    title: string | null;
    alt: string | null;
    kind: "image" | "video" | null;
    aspectRatio: number | null;
    url: string | null;
    width: number | null;
    height: number | null;
  }>;
};

// Query TypeMap
declare global {
  interface SanityQueries {
    '{\n  "settings": *[_type == "siteSettings"][0],\n  "pages": *[_type == "portfolioPage"],\n  "projects": *[_type == "portfolioProject" && defined(slug.current)] | order(order asc),\n  "services": *[_type == "portfolioService"] | order(order asc),\n  "media": *[_type == "portfolioMedia"] {\n    _id, title, alt, kind, aspectRatio,\n    "url": coalesce(image.asset->url, clip.asset->url),\n    "width": image.asset->metadata.dimensions.width,\n    "height": image.asset->metadata.dimensions.height\n  }\n}': SITE_QUERY_RESULT;
  }
}
// Lets @sanity/client releases that predate the global registry read it too
declare module "@sanity/client" {
  interface SanityQueries extends globalThis.SanityQueries {}
}
